import { Public_Sans } from "next/font/google";
import "./globals.css";
import Provider from "@/components/providers/Provider";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});
export const metadata = {
  title: "RemoteIntegrity",
  description: "Generated by RemoteIntegrity",
  icons: {
    icon: "/remoteintegrity.jpg",
    shortcut: "/remoteintegrity.jpg",
    apple: "/remoteintegrity.jpg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.variable} ${publicSans.variable} antialiased`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
